In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
import numpy as np

a=np.arange(16).reshape(4,4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
import numpy as np
a = np.arange(10,60,5).reshape(2,5)
a

array([[10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55]])

In [7]:
import numpy as np 
# Create a 1-D array by passing a list into NumPy's array() function.
print(np.array([8, 4, 6, 0, 2]))

[8 4 6 0 2]


In [8]:
a = np.array([[2,4,5],[1,6,3]])
a

array([[2, 4, 5],
       [1, 6, 3]])

In [9]:
print('Create a 2-D array by passing a list of lists into array().')
A = np.array( [ [1, 2, 3],[4, 5, 6] ] )
print(A)

print('Access elements of the array with brackets.')
print(A[0, 1], A[1, 2])

print('The elements of a 2-D array are 1-D arrays.')
print(A[0])

Create a 2-D array by passing a list of lists into array().
[[1 2 3]
 [4 5 6]]
Access elements of the array with brackets.
2 6
The elements of a 2-D array are 1-D arrays.
[1 2 3]


In [10]:
a = np.array([[2,4,5],[1,6,3]])
a

array([[2, 4, 5],
       [1, 6, 3]])

In [11]:
a = np.array([[3, -1, 4],[1, 5, -9]])
b = np.array([[2, 4, -5, 6],[-1, 7, 9, 3],[3, 2, -7, -2]])
np.dot(a,b)

array([[ 19,  13, -52,   7],
       [-30,  21, 103,  39]])

In [13]:
print('Addition concatenates lists togther')
print([1, 2, 3] + [4, 5, 6])

print('Mutliplication concatenates a list with it self a given number of times')
print([1, 2, 3] * 4)

Addition concatenates lists togther
[1, 2, 3, 4, 5, 6]
Mutliplication concatenates a list with it self a given number of times
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [14]:
x= np.array([-3, 4, 1])
y= np.array([5, 2, 3])
x+10
#y*4
#x+y
#x*y

array([ 7, 14, 11])

In [15]:
x = np.arange(0, 50, 10)
index = np.array([3, 1, 4])
print(x[index])
# A boolean array extracts the elements of 'x' at the same places as 'True'
mask = np.array([True, False, False, True, False])
print(x[mask])

[30 10 40]
[ 0 30]


In [16]:
# Fancy indexing with condition 
y = np.arange(10, 20, 2) #Every other integers from 10 to 20.
print(y)
mask = y > 15 # same as np.array([i > 15 for i in y]).
print (mask)
print (y[mask])
#change the values of 'y' that are larger than 15 to 100.
y[mask] = 100
print(y)

[10 12 14 16 18]
[False False False  True  True]
[16 18]
[ 10  12  14 100 100]


In [17]:
from sklearn  import datasets
# imports  some data to play with
iris = datasets.load_iris()
print(iris.filename)

C:\Users\lenovo-pc\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [18]:
import numpy as np 
iris_data = np.genfromtxt('C:\\Users\\lenovo-pc\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv',
                        delimiter=",", skip_header=1)
print(iris_data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [19]:
import numpy as np 
iris_data = np.genfromtxt('C:\\Users\\lenovo-pc\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv',
                        delimiter=",", skip_header=1)
#print(iris_data)
print("mean of {} is {}".format(iris.feature_names[0], iris_data[:,0].mean()))

mean of sepal length (cm) is 5.843333333333334
